config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  
  namespace :admin do   
    root to: "homes#top"
    patch 'order_details/:id' => 'order_details#update'
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  
  
  scope module: :public do
    root to: "homes#top"
    get 'about'=>"homes#about"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'orders/completed'=>"orders#completed"
    post 'orders/verification'=>"orders#verification"
    resources :orders, only: [:new, :index, :show, :create]
    delete 'cart_items/destroy_all'=>"cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/mypage'=>"customers#show"
    get 'customers/information/edit'=>"customers#edit"
    get 'ccustomers/withdrawal/verification'=>"customers#verification"
    patch 'customers/information'=>"customers#update"
    patch 'customers/withdrawal'=>"customers#withdrawal"
    resources :items, only: [:index, :show]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
    '〒' + postal_code + address + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.price_tax * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  def full_name
    self.first_name + self.last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image
  def price_tax
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  def subtotal
    price * amount
  end
  enum making_status: { not_production: 0, wait_production: 1, production: 2, completed_production: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
  end

  def edit
  end
  
  def create
  end
  
  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.includes(:item)
    @total = @order_details.sum(&:subtotal)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end


end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    admin_root_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    end
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>Admin::Genres#edit</h1>
<p>Find me in app/views/admin/genres/edit.html.erb</p>

app/views/admin/genres/index.html.erb
<main>

</main>

app/views/admin/items/edit.html.erb
<%= render 'admin/header' %>
<div class="container">
  <div class="row mx-5">
    <div class="col-auto my-5 mx-3 text-center table-secondary">
      <caption>商品編集</caption>
    </div>
  </div>
  <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
  <div class="row justify-content-md-center">
    <div class="col-7">
      <table width="100%">
　      <tr>
　        <th class="pb-3">商品画像</th>
　        <td class="pb-3"><%= f.file_field :image, accept: 'image/*' %></td>
　      </tr>
　      <tr>
　        <th class="pb-3">商品名</th>
　        <td class="pb-3"><%= f.text_field :name %></td>
　      <tr>
　      <tr>
　        <th class="pb-3">商品説明</th>
　        <td class="pb-3"><%= f.text_area :introduction %></td>
　      <tr>
　      <tr>
　        <th class="pb-3">税抜価格</th>
　        <td class="pb-3"><%= f.text_field :price %>円</td>
　      </tr>
　      <tr>
　        <th class="pb-3">販売ステータス</th>
　        <td class="pb-3">
　          <%= f.radio_button :is_active, '1' %><%= f.label :is_active, '販売中', value: 1 %>
　          
            <%= f.radio_button :is_active, '0' %><%= f.label :is_active, '販売停止中', value: 0 %>
　        </td>
　      </tr>
　    </table>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <%= f.submit '変更を保存', class: "btn btn-success px-4" %>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<%= render 'admin/header' %>
<div class="container px-5 px-sm-0">
  <div class="row mx-5">
    <div class="col-auto mt-3 mb-2 mx-3 text-center table-secondary">
      <caption>商品一覧</caption>
    </div>
    <div class="col mt-3 mb-2 mx-3 text-right">
      <%= link_to new_admin_item_path, class: "btn btn-success btn-sm" do %>
        新規商品追加
      <% end %>
    </div>
  </div>
  <div class="row mx-5">
    <div class="col-11">
      <table class="table table-hover table-inverse" width="100%">
        <thead class="table-secondary">
          <tr>
            <th width="10%">商品ID</th>
            <th width="40%">商品名</th>
            <th width="30%">税抜価格</th>
            <th width="20%">ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
          <div class="form-group">
            <tr>
              <td>
                <%= item.id %>
              </td>
              <td>
                <%= link_to item.name, admin_item_path(item.id), class: "text-dark border-bottom border-dark" %>
              </td>
              <td>
                <%= item.price.to_s(:delimited) %>
              </td>
              <td>
                <% if item.is_active? %>
                  <p class="text-success">販売中</p>
                <% else %>
                 <p class="text-muted">販売停止中</p>
                <% end %>
              </td>
            </tr>
          </div>
        <% end %>
        <tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<%= render 'admin/header' %>
<div class="container">
  <div class="row mx-5">
    <div class="col-auto my-5 mx-3 text-center table-secondary">
      <caption>新規投稿登録</caption>
    </div>
  </div>
  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
  <div class="row justify-content-md-center">
    <div class="col-7">
      <table width="100%">
　      <tr>
　        <th class="pb-3">商品画像</th>
　        <td class="pb-3"><%= f.file_field :image, accept:'image/*' %></td>
　      </tr>
　      <tr>
　        <th class="pb-3">商品名</th>
　        <td class="pb-3"><%= f.text_field :name %></td>
　      </tr>
　      <tr>
　        <th class="pb-3">商品説明</th>
　        <td class="pb-3"><%= f.text_area :introduction %></td>
　      </tr>
　      <tr>
　        <th class="pb-3">税抜価格</th>
　        <td class="pb-3"><%= f.text_field :price %>円</td>
　      </tr>
　      <tr>
　        <th class="pb-3">販売ステータス</th>
　        <td class="pb-3">
　          <%= f.label :is_active, '販売中', value: 1 %>
            <%= f.radio_button :is_active, '1' %>

            <%= f.label :is_active, '販売停止中', value: 0 %>
            <%= f.radio_button :is_active, '0' %>
　        </td>
　      </tr>
      </table>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <%= f.submit '新規投稿', class: "btn btn-success px-4" %>
  </div>
  <% end %>
</div>
<!-- f.collection_select :保存先のカラム名, 選択肢に使うオブジェクト, :一つ目の引数に渡す値, :選択肢に使うカラム名, include_blank: "選択して下さい" -->

app/views/admin/items/show.html.erb
  <%= render 'admin/header' %>
  <main>
    <div class="container">
      <div class="row mx-5 mt-4 mb-5">
        <div class="col-auto mt-3 mb-2 mx-3 text-center table-secondary">
          <caption>商品詳細</caption>
        </div>
      </div>
      <div class="row">
        <div class="col-4">
            <% if @item.image.attached? %>
              <%= image_tag @item.image, size: "300x200" %>
            <% else %>
              <%= image_tag 'no_image', size: "300x200" %>
            <% end %>
        </div>
        <div class="col-1"></div>
        <div class="col-md-6">
          <table width="100%">
            <tr>
              <th class="py-2" width="30%">商品名</th>
              <td class="py-2"><%= @item.name %></td>
            </tr>
            <tr>
              <th class="py-2">商品説明</th>
              <td class="py-2"><%= @item.introduction %></td>
            </tr>
            <tr>
              <th class="py-2">税込価格</br>(税抜価格)</th>
              <td class="py-2"><%= @item.price_tax.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</td>
            </tr>
            <tr>
              <th class="py-2">販売ステータス</th>
              <td class="pt-3">
                <% if @item.is_active? %>
                  <p class="text-success">販売中</p>
                <% else %>
                  <p class="text-muted">販売停止中</p>
                <% end %>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div class="row justify-content-md-center">
        <%= link_to "編集", edit_admin_item_path(@item.id), class: "btn btn-success px-4 my-4" %>
      </div>
    </div>
  </main>

app/views/admin/orders/show.html.erb
<%= render 'admin/header' %>
<div class="container px-5 px-sm-0">
  <div class="row mx-5">
    <div class="col-auto mt-3 mb-2 mx-3 text-center table-secondary">
      <caption>注文履歴詳細</caption>
    </div>
  </div>
  <div class="row">
    <div class="col-10">
      <table width="100%">
        <tr>
          <th class="pb-2" width="20%">購入者</th>
          <td class="pb-2">
            <%= link_to  admin_customer_path(@order.customer_id), class: "text-dark border-bottom border-dark" do %>
              <%= @order.customer.full_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="pb-2" width="20%">注文日</th>
          <td class="pb-2"><%= @order.created_at.to_s(:datetime_jp) %></td>
        </tr>
        <tr>
          <th class="pb-2" width="20%">
            配送先</br>
            <p></p>
          </th>
          <td class="pb-2">
            〒<%= @order.postal_code %><%= @order.address %></br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th class="pb-2" width="20%">支払方法</th>
          <td class="pb-2"><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th class="pb-4" width="20%">注文ステータス</th>
          <td class="pb-4">
            <%= form_with model: @order,url: admin_order_path(@order), method: :patch do |f| %>
              <%= f.select :status, Order.statuses.keys.map { |k| [t("enums.order.status.#{k}"), k] } %>
              <%= f.submit "更新", class: "btn btn-success btn-sm" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <table width="100%">
        <thead class="table-secondary">
          <tr>
            <th width="35%">商品名</th>
            <th width="15%">単価（税込）</th>
            <th width="5%">数量</th>
            <th width="15%">小計</th>
            <th width="25%">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td class="py-2"><%= order_detail.item.name %></td>
              <td class="py-2"><%= order_detail.price.to_s(:delimited) %></td>
              <td class="py-2"><%= order_detail.amount %></td>
              <td class="py-2"><%= order_detail.subtotal.to_s(:delimited) %></td>
              <td class="py-2">
                <%= form_with model: order_detail,url: admin_path(order_detail.id), method: :patch do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [t("enums.order_detail.making_status.#{k}"), k] } %>
                  <%= f.submit "更新", class: "btn btn-success btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-1"></div>
    <div class="col-auto align-self-end ">
      <table>
        <tr>
          <th class="py-2">商品合計</th>
          <td class="py-2"><%= @total.to_s(:delimited) %> </td>
        </tr>
        <tr>
          <th class="py-2">送料</th>
          <td class="py-2"><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <th class="py-2">請求金額合計</th>
          <td class="py-2"><%= @order.total_payment.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>