config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  
  namespace :admin do   
    root to: "homes#top"
    patch 'order_details/:id' => 'order_details#update'
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  
  
  scope module: :public do
    root to: "homes#top"
    get 'about'=>"homes#about"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'orders/completed'=>"orders#completed"
    post 'orders/verification'=>"orders#verification"
    resources :orders, only: [:new, :index, :show, :create]
    delete 'cart_items/destroy_all'=>"cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/mypage'=>"customers#show"
    get 'customers/information/edit'=>"customers#edit"
    get 'ccustomers/withdrawal/verification'=>"customers#verification"
    patch 'customers/information'=>"customers#update"
    patch 'customers/withdrawal'=>"customers#withdrawal"
    resources :items, only: [:index, :show]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
    '〒' + postal_code + address + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.price_tax * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  def full_name
    self.first_name + self.last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image
  def price_tax
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  def subtotal
    price * amount
  end
  enum making_status: { not_production: 0, wait_production: 1, production: 2, completed_production: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
  end

  def edit
  end
  
  def create
  end
  
  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    end
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_header.html.erb
  <body>
    <% if admin_signed_in? %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-white bg-white border-bottom border-dark">
          <div class="container-fluid pt-4 pb-4">
            <a class="navbar-brand" href="/admin">
              <span class="text-dark pt-2 pb-2 pl-4 pr-4 rounded border border-dark">NaganoCake</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="pr-3">
                  <%= link_to admin_items_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    商品一覧
                  <% end %>
                </li>
                <li class="pr-3 pl-3">
                  <%= link_to admin_customers_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    会員一覧
                  <% end %>
                </li>
                <li class="pr-3 pl-3">
                  <%= link_to admin_root_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    注文履歴一覧
                  <% end %>
                </li>
                <li class="pl-3">
                  <%= link_to destroy_admin_session_path, method: :delete,class: "nav-link text-dark rounded border border-black-50" do %>
                    ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% else %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-white bg-white border-bottom border-dark">
          <div class="container-fluid pt-4 pb-4">
            <a class="navbar-brand" href="/">
              <span class="text-dark pt-2 pb-2 pl-4 pr-4 rounded border border-dark">NaganoCake</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="pr-3">
                  <%= link_to about_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    About
                  <% end %>
                </li>
                <li class="pr-3 pl-3">
                  <%= link_to items_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    商品一覧
                  <% end %>
                </li>
                <li class="pr-3 pl-3">
                  <%= link_to new_customer_registration_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    新規登録
                  <% end %>
                </li>
                <li class="pl-3">
                  <%= link_to new_admin_session_path,class: "nav-link text-dark rounded border border-black-50" do %>
                    ログイン
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>      
    <% end %>
  </body>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>