config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  
  namespace :admin do   
    root to: "homes#top"
    patch 'order_details/:id' => 'order_details#update'
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  
  
  scope module: :public do
    root to: "homes#top"
    get 'about'=>"homes#about"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'orders/completed'=>"orders#completed"
    post 'orders/verification'=>"orders#verification"
    resources :orders, only: [:new, :index, :show, :create]
    delete 'cart_items/destroy_all'=>"cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/mypage'=>"customers#show"
    get 'customers/information/edit'=>"customers#edit"
    get 'ccustomers/withdrawal/verification'=>"customers#verification"
    patch 'customers/information'=>"customers#update"
    patch 'customers/withdrawal'=>"customers#withdrawal"
    resources :items, only: [:index, :show]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
    '〒' + postal_code + address + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.price_tax * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  def full_name
    self.first_name + self.last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image
  def price_tax
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  def subtotal
    price * amount
  end
  enum making_status: { not_production: 0, wait_production: 1, production: 2, completed_production: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
  end

  def edit
  end
  
  def create
  end
  
  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.includes(:item)
    @total = @order_details.sum(&:subtotal)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    end
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
  <%= render 'admin/header' %>
  <main>
    <div class="container">
      <div class="row mx-5">
        <div class="col-auto mt-4 mb-3 mx-3 text-center table-secondary">
          <caption><%= @customer.full_name %>さんの会員情報編集</caption>
        </div>
      </div>
      <div class="row mx-5">
        <div class="col-9">
          <table width="100%">
            <%= form_with model: @customer,url: admin_customer_path(@customer), method: :patch do |f| %>
            <tr>
              <th class="pb-3">会員ID</th>
              <td class="pb-3"><%= @customer.id %></td>
            </tr>
            <tr>
              <th class="pb-3">氏名</th>
              <td class="pb-3"><%= f.text_field :last_name %></td> 
              <td class="pb-3"><%= f.text_field :first_name %></td>
            </tr>
            <tr>
              <th class="pb-3">フリガナ</th>
              <td class="pb-3"> <%= f.text_field :last_name_kana %></td>
              <td class="pb-3"><%= f.text_field :first_name_kana %></td>
            </tr>
            <tr>
              <th class="pb-3">郵便番号</th>
              <td class="pb-3"><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <th class="pb-3">電話番号</th>
              <td class="pb-3"><%= f.text_field :telephone_number %></td>
            </tr>
            <tr>
              <th class="pb-3">メールアドレス</th>
              <td class="pb-3"><%= f.text_field :email %></td>
            </tr>
            <tr>
              <th class="pb-3">住所</th>
              <td class="pb-3"><%= f.text_field :address %></td>
            </tr>
            
            <tr>
              <th class="pb-3">退会ステータス</th>
              <td class="pb-3">
　              <%= f.radio_button :is_deleted, 'false' %><%= f.label :is_deleted, '有効', value:false %>

                <%= f.radio_button :is_deleted, 'true' %><%= f.label :is_deleted, '退会', value: true %>
              </td>
            <tr>
            <tr>
              <th class="pb-5"></th>
              <td class="pb-5"><%= f.submit '変更を保存', class: "btn btn-success px-4 py-2" %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </main>

app/views/admin/customers/index.html.erb
<%= render 'admin/header' %>
<div class="container px-5">
  <div class="row mx-5">
    <div class="col-auto mt-3 mb-2 mx-3 text-center table-secondary">
      <caption>会員一覧</caption>
    </div>
  </div>
  <div class="row mx-5">
    <div class="col-11">
      <table class="table table-hover table-inverse" width="100%">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
                <%= customer.id %>
              </td>
              <td>
                <%= link_to customer.full_name, admin_customer_path(customer.id), class: "text-dark border-bottom border-dark" %>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>
                <% if customer.is_deleted? %>
                  <p class="text-muted">退会</p>
                <% else %>
                　<p class="text-success">有効</p>
                <% end %>
              </td>
            </tr>
          <% end %>
          <%= paginate @customers %>
        <tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
  <%= render 'admin/header' %>
  <main>
    <div class="container">
      <div class="row mx-5">
        <div class="col-auto mt-3 mb-2 mx-3 text-center table-secondary">
          <caption><%= @customer.full_name %>さんの会員詳細</caption>
        </div>
      </div>
      <div class="row mx-5">
        <div class="col-8">
          <table width="100%">
            <tr>
              <th class="pb-3">会員ID</th>
              <td class="pb-3"><%= @customer.id %></td>
            </tr>
            <tr>
              <th class="pb-3">氏名</th>
              <td class="pb-3">
                <%= @customer.last_name %>
                <%= @customer.first_name %>
              </td>
            </tr>
            <tr>
              <th class="pb-3">フリガナ</th>
              <td class="pb-3">
                <%= @customer.last_name_kana %>
                <%= @customer.first_name_kana %>
              </td>
            </tr>
            <tr>
              <th class="pb-3">郵便番号</th>
              <td class="pb-3"><%= @customer.postal_code %></td>
            </tr>
            <tr>
              <th class="pb-3">住所</th>
              <td class="pb-3"><%= @customer.address %></td>
            </tr>
            <tr>
              <th class="pb-3">電話番号</th>
              <td class="pb-3"><%= @customer.telephone_number %></td>
            </tr>
            <tr>
              <th class="pb-3">メールアドレス</th>
              <td class="pb-3"><%= @customer.email %></td>
            </tr>
            <tr>
              <th class="pb-3">会員ステータス</th>
              <td class="pb-3">
                <% if @customer.is_deleted? %>
                  <p class="text-muted pt-2">退会</p>
                <% else %>
                　<p class="text-success pt-2">有効</p>
                <% end %>
              </td>
            </tr>
            <tr>
              <th></th>
              <td><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success  btn-sm px-3" %></td>
              <td><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary btn-sm px-3" %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </main>